theme: jekyll-theme-cayman
permalink: /noticias/:year/:month/:day/:title/
title: RECONECTA
description: Reservas conectadas para una gestión pesquera resiliente en Mallorca

pleamar_ack: "Este proyecto se desarrolla con la colaboración de la Fundación Biodiversidad del Ministerio para la Transición Ecológica y el Reto Demográfico, a través del Programa Pleamar, y se cofinancia por la Unión Europea por el FEMPA (Fondo Europeo Marítimo, de Pesca y de Acuicultura)."
pleamar_disclaimer: "Las opiniones y documentación aportadas en esta publicación son de exclusiva responsabilidad de la persona o personas que ostenten su autoría y no reflejan necesariamente los puntos de vista de las entidades que apoyan económicamente el proyecto."

links:
  fundacion_biodiversidad: "https://fundacion-biodiversidad.es/"
  miteco: "https://www.miteco.gob.es/"
  programa_pleamar: "https://fundacion-biodiversidad.es/ayudas/programa-pleamar/"
  union_europea: "https://european-union.europa.eu/"
  fempa: "https://www.mapa.gob.es/es/pesca/temas/fondos-europeos/fempa/"
